<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>try-with-resources на кошках</title>
	</head>

	<body>
		<h1>
			<big>
				<a href="/#java-twr" title="Перейти к оглавлению">&larr;</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="/" title="Перейти на главную страницу">&#8962;</a>
			</big>
		</h1>

		<hr>

		<h1>
			<a href="http://flaz14.github.io/java-twr/java-twr.html">
				try-with-resources на кошках
			</a>
		</h1>
		
		<h3>[2018, Февраль]</h3>
		
		<h2>Тренируйся лучше... на кошках</h2>

		<p>
			Java 8 уже прочно закрепилась в мире промышленного программирования. А по планете во всю шагает Java 9. Тем 
			не менее, не пропадает ощущение, что каждая новая версия Java - это не новые возможности, а исправления 
			недостатков предыдущей версии. Я прочитал про конструкцию <strong>try-with-resources</strong> (далее по 
			тексту - <strong>TWR</strong> в одной умной книжке
			<sup id="footnote-1-top"><a href="#footnote-1-bottom">[1]</a></sup>. 
			Затем прочитал туториал Oracle <sup id="footnote-2-top"><a href="#footnote-2-bottom">[2]</a></sup>. 
			Но полностью не понял, что TWR за зверь такой. Так что ничего не оставалось, как учиться самому на маленьких
			примерах <sup id="footnote-3-top"><a href="#footnote-3-bottom">[3]</a></sup>. 	

		<h2>Переменные нужны, переменные важны</h2>
		
		<p>
			Начнем с самого простого примера <sup id="footnote-4-top"><a href="#footnote-4-bottom">[4]</a></sup>.

<h4 id="listing-1">Листинг 1 - типы переменных имеют значение</h4>
<pre>
     1	public class VariablesTest {
     2		public static void main(String ignored[]) {
     3			try( MyAutoCloseable resource = new MyAutoCloseable() ) { }
     4			
     5			//try( AutoCloseable resource = new MyAutoCloseable() ) { }
     6		
     7			//try( new MyAutoCloseable() ) { }
     8		}
     9	}
    10	
    11	class MyAutoCloseable implements AutoCloseable {
    12		@Override
    13		public void close() {
    14			System.out.println("&gt;&gt;&gt; close()"); 
    15		}
    16	}
</pre>

		<p>
			Действительно, все просто. Программа напечатает <tt>&gt;&gt;&gt; close()</tt>. Если мы расскоментируем 
			строку <b>№5</b>, то получим ошибку во время компиляции:

<pre>
VariablesTest.java:5: error: unreported exception Exception; must be caught or declared to be thrown
		try( AutoCloseable resource = new MyAutoCloseable() ) { }
		                   ^
  exception thrown from implicit call to close() on resource variable 'resource'
1 error
</pre>
		
		<p>
			Если же раскомментируем строчку <b>№7</b>, то компилятор "порадует" таким известием:

<pre>
VariablesTest.java:7: error: illegal start of type
		try( new MyAutoCloseable() ) { }
		     ^
VariablesTest.java:7: error: = expected
		try( new MyAutoCloseable() ) { }
		         ^
</pre>

		<p>
			Без явного объявления переменных в TWR обойтись нельзя. Тип переменной тоже имеет значение. Класс 
			<code>MyAutoCloseable</code> реализует <code>AutoCloseable</code>. Но объявление переменной с типом 
			интерфейса приводит к ошибке компиляции, посколько метод <code>close()</code> интерфейса декларирует 
			исключение <code>Exception</code>. А в методе <code>close()</code> класса <code>MyAutoCloseable</code> об 
			исключении не сказано.

		<h2>Переменные ОЧЕНЬ нужны</h2>
		
		<p>
			От порядка объявления переменных в TWR зависит порядок закрытия ресурсов. Оно и понятно: ресурсы должны 
			освобождаться в порядке, обратном их созданию. Это проиллюстрировано в <a href="#listing-2">листинге 2</a>.
			
<h4 id="listing-2">Листинг 2 - порядок объявления переменных имеет значение</h4>
<pre>
     1	public class OrderingTest {
     2		public static void main(String args[]) {
     3			System.out.println("--- First - Second");
     4			try ( 
     5				First first = new First();
     6				Second second = new Second();
     7			) {}
     8			
     9			System.out.println("--- Second - First");
    10			try (
    11				Second second = new Second();
    12				First first = new First();
    13			) {}
    14			
    15			System.out.println("--- variable for First is missed");
    16			try (
    17				Second second = new Second(
    18					new First()
    19				)
    20			) {}
    21		}
    22	}
    23	
    24	class First implements AutoCloseable {
    25		@Override
    26		public void close() {
    27			System.out.println("&gt;&gt;&gt; First.close()");
    28		}
    29	}
    30	
    31	class Second implements AutoCloseable {
    32		public Second() {}
    33		
    34		public Second(First first) {}
    35		
    36		@Override
    37		public void close() {
    38			System.out.println("&gt;&gt;&gt; Second.close()");
    39		}
    40	}
</pre>

		<p>
			Программа напечатает:

<pre>
--- First - Second
&gt;&gt;&gt; Second.close()
&gt;&gt;&gt; First.close()
--- Second - First
&gt;&gt;&gt; First.close()
&gt;&gt;&gt; Second.close()
--- variable for First is missed
&gt;&gt;&gt; Second.close()
</pre>

		<p>
			Обратим внимание на случай <i>--- variable for First is missed</i>. Экземпляр класса <code>First</code>
			(созданный в строке <b>№18</b>) не был закрыт. А все из-за того, что мы не завели для него отдельную 
			переменную,	а передали его в конструктор <code>Second</code> напрямую. Конечно, в реальном коде такая 
			ситуация маловероятна. Т.е.	в методе <code>close()</code> промышленного варианта класса <code>Second</code> 
			должен явно вызываться 	одноименный метод класса <code>First</code>, и так далее по цепочке. Но что если 
			метод <code>close()</code> класса <code>Second</code> выбросит исключение до того, как вызовет 
			<code>close()</code> на экземпляре <code>First</code>? Ресурс <code>First</code> останется незакрытым. 
			Решение одно: объявлять переменные для каждого ресурса отдельно.

		<h2>Полиморфизм в действии</h2>

		<p>
			Несмотря на то, что тип переменной в TWR имеет значение для компилятора в плане обрабатываемых исключений,
			полиморфизм никуда не исчез. В примере, приведенном в <a href="#listing-3">листинге 3</a>, рассмотрены три 
			случая: анонимный класс, "отдельностоящий" класс, который непосредственно реализует 
			<code>AutoCloseable</code>,	и класс, который реализует <code>AutoCloseable</code> через интерфейс-посредник
			<sup id="footnote-5-top"><a href="#footnote-5-bottom">[5]</a></sup>.
		
<h4 id="listing-3">Листинг 3 - пример полифорфизма в TWR</h4>
<pre>
     1	public class PolymorphismTest {
     2		public static void main(String ignored[]) {
     3			try (
     4				SomeAutoCloseable resource = new SomeAutoCloseable() {
     5					@Override
     6					public void close() { System.out.println("&gt;&gt;&gt; Anonymous close()"); }
     7				}
     8			) {}
     9			
    10			try ( SomeAutoCloseable resource = new StandaloneCloseAble() ) {}
    11			
    12			try ( InterfaceForAutoCloseable tricky = new TrickyAutoCloseable() ) {}
    13		}
    14	}
    15	
    16	class SomeAutoCloseable implements AutoCloseable {
    17		@Override
    18		public void close() { System.out.println("&gt;&gt;&gt; Other.close()"); }
    19	}
    20	
    21	class StandaloneCloseAble extends SomeAutoCloseable {
    22		@Override
    23		public void close() { System.out.println("&gt;&gt;&gt; Standalone close()"); }
    24	}
    25	
    26	interface InterfaceForAutoCloseable extends AutoCloseable { 
    27		@Override
    28		void close();
    29	}
    30	
    31	class TrickyAutoCloseable implements InterfaceForAutoCloseable {
    32		@Override
    33		public void close() { System.out.println("&gt;&gt;&gt; TrickyAutoCloseable.close()"); }
    34	}
</pre>

		<p>
			Результат работы программы предсказуем. Всегда вызывается актуальный метод класса:

<pre>
&gt;&gt;&gt; Anonymous close()
&gt;&gt;&gt; Standalone close()
&gt;&gt;&gt; TrickyAutoCloseable.close()
</pre>

		<h2>Лямбда-выражения!</h2>
		
		<p>
			Да, в TWR можно творить все, что угодно. В том числе объявлять лямбда-выражения. Вгляните-ка на 
			<a href="#listing-4">листинг 4</a>.
			
<h4 id="listing-4">Листинг 4 - лямбда-выражения в TWR</h4>
<pre>
     1	public class LambdaTest {
     2		public static void main(String ignored[]) {
     3			System.out.println("--- Lambda #1 ---");
     4			try (
     5				MyAutoCloseable resource = () -> {
     6					System.out.println("&gt;&gt;&gt; Lambda #1 close()");
     7				}
     8			) {}
     9			System.out.println("-----------------");
    10	
    11			System.out.println("--- Lambda #2 ---");
    12			try (
    13				MyAutoCloseable resource = () -> {
    14					System.out.println("&gt;&gt;&gt; Lambda #2 close()");
    15					System.out.println("Stacktrace:");
    16					throw new IllegalStateException("Just for illustration");
    17				}
    18			) {}
    19		}
    20	}
    21	
    22	interface MyAutoCloseable extends AutoCloseable {
    23		@Override
    24		void close();
    25	}
</pre>

		<p>
			Тут тоже все вполне ожидаемо:

<pre>
--- Lambda #1 ---
&gt;&gt;&gt; Lambda #1 close()
-----------------
--- Lambda #2 ---
&gt;&gt;&gt; Lambda #2 close()
Stacktrace:
Exception in thread "main" java.lang.IllegalStateException: Just for illustration
	at LambdaTest.lambda$main$1(LambdaTest.java:16)
	at LambdaTest.main(LambdaTest.java:18)
</pre>

		<p>
			Стэктрэйс меня не огорчил, но и не порадовал. Раз уж лямбда-выражение определено в TWR, я ожидал увидеть 
			в стэктрэйсе что-нибудь наподобие <code>LambdaTest.lambda$main$&lt;twr&gt;2$1(LambdaTest.java:16)</code>. 
			Т.е. я ожидал увидеть подсказку, что лямбда-выражение было определено не просто в методе 
			<code>main()</code>, а именно внутри TWR (который выполнился вторым по счету; хотя и без циферки было бы 
			неплохо).
		
		<h2>final не нужен</h2>

		<p>
			Неизменяемость нынче в моде. В Java модификатор <strong>final</strong> можно добавлять к чему угодно. Но в 
			случае с TWR это не имеет никакого смысла. Объявленную в TWR переменную не позволит изменить компилятор, 
			неважно, объявлена она как <code>final</code> или нет. Что и проиллюстрировано в 
			<a href="#listing-5">листинге 5</a>.

<h4 id="listing-5">Листинг 5 - пример использования final</h4>
<pre>
     1	public class FinalModifierTest {
     2		public static void main(String ignored[]) {
     3			try( final MyAutoCloseable my = new MyAutoCloseable() ) {}
     4			
     5			// Compile-time error: auto-closeable resource my may not be assigned
     6			/* 
     7			try( MyAutoCloseable my = new MyAutoCloseable() ) {
     8				my = null;
     9			}
    10			*/
    11		}
    12	}
    13	
    14	class MyAutoCloseable implements AutoCloseable {
    15		@Override
    16		public void close() {}
    17	}
</pre>

		<p>
			Об этом сказано в 
			<a href="https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3">JLS</a>: 
			<cite>A variable declared in a resource specification is implicitly declared final (§4.12.4) if it is not 
			explicitly declared final.</cite>

		<h2>Магия null</h2>
		
		<p>
			Как сказано в 
			<a href="https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3">JLS</a>: 
			<cite>A resource is closed only if it initialized to a non-null value.</cite>
			Согласно спецификации, программа, приведенная в <a href="#listing-6">листинге 6</a>, ничего не напечатает.
			И это правильно. Вызов какого-либо метода на <code>null</code> не имеет смысла. Вызов <code>close()</code> 
			на заведомо нулевой ссылке - тоже.

<h4 id="listing-6">Листинг 6 - null игнорируется во время автоматического закрытия ресурсов</h4>
<pre>
     1	public class NullPointer2Test {
     2		public static void main(String ignored[]) {
     3			try(MyResource resource = getMyResource()) {
     4			}
     5		}
     6		
     7		private static MyResource getMyResource() {
     8			return null;
     9		}
    10	}
    11	
    12	class MyResource implements AutoCloseable {
    13		@Override
    14		public void close() {
    15			System.out.println("&gt;&gt;&gt; MyResource.close()");
    16		}
    17	}
</pre>
	
		<p>
			Рассмотрим еще один пример. Я воспроизвел его из упомянутой в начале статьи умной книжки и поместил в 
			<a href="#listing-7">листинг 7</a>.
			
<h4 id="listing-7">Листинг 7 - пример неотвратимого NullPointerException</h4>
<pre>
     1	import java.io.InputStream;
     2	import java.io.IOException;
     3	
     4	public class NullPointer1Test {
     5		public static void main(String ignored[]) throws IOException {
     6			try(InputStream i = getNullStream()) {
     7				i.available();
     8			}
     9		}
    10		
    11		private static InputStream getNullStream() { 
    12			return null;
    13		}
    14	}
</pre>

		<p>
			В книге в комментариях к примеру сказано:
			<blockquote>
				<p>
					Один из аспектов конструкции TWR - появление улучшенных стектрейсов и заблокированных исключений. До
					Java 7 информация об исключении могла быть поглощена при обработке ресурсов. Такой вариант не 
					исключен и с TWR, поэтому стековые следы были усовершенствованы. Теперь вы можете просматривать в
					исключениях и информацию о типах, которая ранее просто терялась.
					
				<p>
					Например, рассмотрим следующий фрагмент кода, в котором нулевой <code>InputStream</code> 
					возвращается из метода:
					
				<p>
					<i>далее идет то же, что и в <a href="#listing-7">листинге 7</a></i>
				
				<p>
					В результате получится улучшенный стектрейс, в котором мы увидим заблокированное исключение 
					<code>NullPointerException</code> (сокращенно - NPE):
					
				<p>
					<i>далее приведен стектрейс, но он в корне отличается от того, что реально получается в результате
					работы кода из <a href="#listing-7">листинга 7</a></i>	
			</blockquote>
			
		<p>
			Запустим пример и получим:
			
<pre>
Exception in thread "main" java.lang.NullPointerException
	at NullPointer1Test.main(NullPointer1Test.java:7)
</pre>
		
		<p>
			Никакого упоминания о <strong>Suppressed</strong> нет. Старый добрый <code>NullPointerException</code> 
			никуда не делся. Я ожидал, что нулевая ссылка на <code>i</code> будет "отловлена и подавлена" в TWR в месте 
			создания ресурса, т.е. в строке <b>№6</b> <a href="#listing-7">листинга 7</a>. Но нет, стэктрэйс ведет в 
			строку <b>№7</b>, т.е. в блок <em>try</em>, где переменная <code>i</code> была использована.
		
		<p>
			Т.о. <code>null</code>-значения в TWR вполне допустимы. То ли авторы не разобрались в теме, то ли 
			переводчики	напутали... Как бы то ни было, "подавление" исключений в TWR - совсем другой случай. Рассмотрим 
			его в следующем разделе.
			
		<h2>Suppressed exceptions</h2>
		
		<p>
			"Подавление" исключений	имеет смысл лишь тогда, когда исключений возникает несколько. Легче всего 
			разобраться на примере. Об этом уже рассказано в официальной статье от Oracle: 
			<a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html#suppressed-exceptions">
			The try-with-resources Statement</a>.
			Но пример там выбран не сильно удачный. Он великоват, уловить суть непросто. Я сделал свой пример совсем 
			маленьким.

<h2 id="listing-8">Листинг 8 - пример подавляемого исключения</h2>			
<pre>
     1	public class SuppressedExceptionTest {
     2		public static void main(String ignored[]) {
     3			try(MyResource resource = new MyResource()) {
     4				System.out.println("&gt;&gt;&gt; try-block");
     5				throw new IllegalStateException("Exception from try-block");
     6			} finally {
     7				System.out.println("&gt;&gt;&gt; finally-block");
     8			}
     9		}
    10	}
    11	
    12	class MyResource implements AutoCloseable {
    13		@Override
    14		public void close() {
    15			System.out.println("&gt;&gt;&gt; MyResource.close()");
    16			throw new IllegalStateException("Exception from MyResource.close()");
    17		}
    18	}
</pre>
		
		<p>
			Тестовая программа напечатает:

<pre>
&gt;&gt;&gt; try-block
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; finally-block
Exception in thread "main" java.lang.IllegalStateException: Exception from try-block
	at SuppressedExceptionTest.main(SuppressedExceptionTest.java:5)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource.close()
		at MyResource.close(SuppressedExceptionTest.java:16)
		at SuppressedExceptionTest.main(SuppressedExceptionTest.java:6)
</pre>

		<p>
			Что же произошло? Первым делом выполнился блок <em>try</em>. Затем в строке <b>№5</b> было выброшено 
			исключение с текстом <i>Exception from try-block</i>. Но это исключение не "всплыло" наверх сразу. Блок 
			<em>finally</em> выполняется всегда, независимо от того, было ли в <em>try</em> выброшено исключение или же
			возвращено значение посредством <em>return</em>. Но перед выполнением <em>finally</em> было произведено
			автоматическое закрытие ресурса, созданного в TWR. И во время автоматического закрытия произошло еще одно 
			исключение, с текстом <i>Exception from MyResource.close()</i>. Получается интересная ситуация: выброшены
			два исключения: одно родом из блока <em>try</em>, а другое - из безымянного блока автоматического закрытия
			(назовем его <em>pre-finally</em>). С ними надо что-то делать. Приведем повторно цитату из умной книжки:
			<blockquote>
				<p>
					До Java 7 информация об исключении могла быть поглощена при обработке ресурсов. Такой вариант не
					исключен и с TWR, поэтому стековые следы были усовершенствованы. Теперь вы можете просматривать в 
					исключениях	информацию о типах, которая ранее просто терялась.
			</blockquote>
		
		<p>
			Да, так и есть. Первичным, если так можно выразиться, исключением был и остался 
			<i>Exception from try-block</i>. За вторичное исключение, которое произошло позже в хронологическом порядке,
			принят <i>Exception from MyResource.close()</i> (и вообще, это исключение вторично уже просто потому, что 
			<em>pre-finally</em> - служебный автоматически генерируемый компилятором блок, не имеющий непосредственного
			отношения к логике программы). На вершине стэка вызовов находится строчка:

<pre>
		at MyResource.close(SuppressedExceptionTest.java:16)
</pre>

		<p>
			<b>№16</b> ведет в строку <code>throw new IllegalStateException("Exception from MyResource.close()");</code> 
			<a href="#listing-8">листинга 8</a>, которая находится в методе <code>close()</code> класса 
			<code>MyResource</code>. Ниже в стэктрэйсе идет:

<pre>
			at SuppressedExceptionTest.main(SuppressedExceptionTest.java:6)
</pre>

		<p>
			Хм... Строка <b>№6</b> - это самое начало блока <em>finally</em>. Поскольку блок автоматического закрытия 
			ресурсов (названный мною <em>pre-finally</em>) генерируется компилятором, то и номеров строчек исходного 
			текста предоставить компилятор не в силах. Вот и "приписали" <em>pre-finally</em> к <em>finally</em>.

		<h2>Multiple suppressed exceptions</h2>
		
		<p>
			А могут ли появится в стэктрэйсе несколько исключений? Да пожалуйста! Пример, приведенный в 
			<a href="#listing-9">листинге 9</a>, отлично это демонстрирует:
			
<h4 id="listing-9">Листинг 9 - пример нескольких подавляемых исключений</h4>
<pre>
     1	public class MultipleSuppressedExceptionsTest {
     2		public static void main(String ignored[]) {
     3			try (
     4				MyResource apple = new MyResource("apple");
     5				MyResource banana = new MyResource("banana");
     6				MyResource orange = new MyResource("orange");
     7				MyResource cherry = new MyResource("cherry");
     8			) { 
     9				System.out.println("&gt;&gt;&gt; try-block");
    10				throw new IllegalStateException("Exception from try-block");
    11			} finally {
    12				System.out.println("&gt;&gt;&gt; finally-block");
    13			}
    14		}
    15	}
    16	
    17	class MyResource implements AutoCloseable {
    18		private final String id;
    19		
    20		public MyResource(String id) { this.id = id;}
    21		
    22		@Override
    23		public void close() { 
    24			System.out.println("&gt;&gt;&gt; MyResource [" + id + "] close()"); 
    25			throw new IllegalStateException("Exception from MyResource [" + id + "]");
    26		}
    27	}
</pre>

		<p>
			Запустим пример и увидим:
<pre>
&gt;&gt;&gt; try-block
&gt;&gt;&gt; MyResource [cherry] close()
&gt;&gt;&gt; MyResource [orange] close()
&gt;&gt;&gt; MyResource [banana] close()
&gt;&gt;&gt; MyResource [apple] close()
&gt;&gt;&gt; finally-block
Exception in thread "main" java.lang.IllegalStateException: Exception from try-block
	at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:10)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [cherry]
		at MyResource.close(MultipleSuppressedExceptionsTest.java:25)
		at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:11)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [orange]
		at MyResource.close(MultipleSuppressedExceptionsTest.java:25)
		at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:11)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [banana]
		at MyResource.close(MultipleSuppressedExceptionsTest.java:25)
		at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:11)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [apple]
		at MyResource.close(MultipleSuppressedExceptionsTest.java:25)
		at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:11)
</pre>

		<p>
			Все осталось на месте и ничего не потерялось. Отлично! Если же закомментировать строчку <b>№10</b>, то на 
			вершине	стэка вызовов окажется исключение, возникшее при закрытии ресурса, который был иницилизирован 
			последним в TWR, т.е. "вишневое". К сожалению, при таком раскладе часть информации об остальных исключениях 
			("апельсиновое", "банановое", "яблочное") теряется: ни тебе имен методов, ни тебе номеров строчек исходного 
			текста.	Какие-то вместо них <i>... 2 more</i> невнятные. Хорошо хоть имена классов и сообщения исключений 
			оставили. Логично, что все исключения относятся	к одному и тому же TWR. Но все равно не понимаю такой 
			мелочной экономии.

<pre>
&gt;&gt;&gt; try-block
&gt;&gt;&gt; MyResource [cherry] close()
&gt;&gt;&gt; MyResource [orange] close()
&gt;&gt;&gt; MyResource [banana] close()
&gt;&gt;&gt; MyResource [apple] close()
&gt;&gt;&gt; finally-block
Exception in thread "main" java.lang.IllegalStateException: Exception from MyResource [cherry]
	at MyResource.close(MultipleSuppressedExceptionsTest.java:25)
	at MultipleSuppressedExceptionsTest.main(MultipleSuppressedExceptionsTest.java:11)
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [orange]
		... 2 more
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [banana]
		... 2 more
	Suppressed: java.lang.IllegalStateException: Exception from MyResource [apple]
		... 2 more
</pre>
		
		<h2>finally "съедает" всё</h2>
		
		<p>
			Напоследок, попробуем выполнить еще несколько примеров, постепенно увеличивая степень безумия и уменьшая 
			степень практического смысла. Для начала попробуем выбросить исключение в блоке <em>finally</em> основного
			метода, т.е. метода <code>main()</code>:

<h4 id="listing-11">Листинг 11 - finally "съедает" try</h4>
<pre>
     1	public class MegaSuppressedExceptions {
     2		public static void main(String ignored[]) {
     3			try ( MyResource resource = new MyResource() ) {
     4				System.out.println("&gt;&gt;&gt; try-block");
     5				throw new IllegalStateException("Exception from try-block");
     6			} finally {
     7				System.out.println("&gt;&gt;&gt; finally-block");
     8				throw new IllegalStateException("Exception from finally-block");
     9			}
    10		}
    11	}
    12	
    13	class MyResource implements AutoCloseable {
    14		@Override
    15		public void close() {
    16			System.out.println("&gt;&gt;&gt; MyResource.close()");
    17		}
    18	}
</pre>
	
		<p>
			В результате увидим, что исключение, возникшее в блоке <em>try</em>, было бесследно "съедено" исключением, 
			возникшем в блоке <em>finally</em>:

<pre>
&gt;&gt;&gt; try-block
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; finally-block
Exception in thread "main" java.lang.IllegalStateException: Exception from finally-block
	at MegaSuppressedExceptions.main(MegaSuppressedExceptions.java:8)
</pre>

		<p>
			Приправим предыдущий пример AutoCloseable'ом.

<h4 id="listing-11">Листинг 11 - finally "съедает" Suppressed exception</h4>			
<pre>
     1	public class SuperDuperSuppressedExceptions {
     2		public static void main(String ignored[]) {
     3			try ( MyResource resource = new MyResource() ) {
     4				System.out.println("&gt;&gt;&gt; try-block");
     5				throw new IllegalStateException("Exception from try-block");
     6			} finally {
     7				System.out.println("&gt;&gt;&gt; finally-block");
     8				throw new IllegalStateException("Exception from finally-block");
     9			}
    10		}
    11	}
    12	
    13	class MyResource implements AutoCloseable {
    14		@Override
    15		public void close() {
    16			System.out.println("&gt;&gt;&gt; MyResource.close()");
    17			throw new IllegalStateException("Exception from MyResource.close()");
    18		}
    19	}
</pre>

		<p>
			Запустим и увидим:
<pre>
&gt;&gt;&gt; try-block
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; finally-block
Exception in thread "main" java.lang.IllegalStateException: Exception from finally-block
	at SuperDuperSuppressedExceptions.main(SuperDuperSuppressedExceptions.java:8)
</pre>

		<p>
			Печальная картина... Хорошо хоть, что автоматическое закрытие ресурсов выполнилось. В остальном же 
			<em>finally</em> безжалостно сожрал всех. Никаких следов о <i>Exception from try-block</i> и 
			<i>Exception from MyResource.close()</i> не осталось.
		
		<p>
			А теперь попробуем выбросить исключение в блоке <em>finally</em> метода <code>close()</code>.

<h4 id="listing-12">Листинг 12 - finally "съедает" try и в AutoCloseable</h4>
<pre>
     1	public class ExtremeSuppressedExceptions {
     2		public static void main(String ignored[]) {
     3			try ( MyResource resource = new MyResource() ) {
     4				System.out.println("&gt;&gt;&gt; main()");
     5				throw new IllegalStateException("Exception from main()");
     6			}
     7		}
     8	}
     9	
    10	class MyResource implements AutoCloseable {
    11		@Override
    12		public void close() {
    13			System.out.println("&gt;&gt;&gt; MyResource.close()");
    14			try {
    15				System.out.println("&gt;&gt;&gt; try-block from MyResource");
    16				throw new IllegalStateException("Exception from try-block from MyResource");
    17			}
    18			finally {
    19				System.out.println("&gt;&gt;&gt; finally-block from MyResource");
    20				throw new IllegalStateException("Exception from finally-block from MyResource");
    21			}
    22		}
    23	}
</pre>

<pre>
&gt;&gt;&gt; main()
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; try-block from MyResource
&gt;&gt;&gt; finally-block from MyResource
Exception in thread "main" java.lang.IllegalStateException: Exception from main()
	at ExtremeSuppressedExceptions.main(ExtremeSuppressedExceptions.java:5)
	Suppressed: java.lang.IllegalStateException: Exception from finally-block from MyResource
		at MyResource.close(ExtremeSuppressedExceptions.java:20)
		at ExtremeSuppressedExceptions.main(ExtremeSuppressedExceptions.java:6)
</pre>

		<p>
			Как видим, исключение, выброшенное в блоке <em>try</em> метода <code>close()</code> было "съедено" 
			исключением, выброшенным в блоке <em>finally</em> метода <code>close()</code>. А последнее, в свою очередь, 
			было подавлено исключением, выброшенным в блоке <em>try</em> метода <code>main()</code>.
			
		<h2>Ложка меда напоследок</h2>
		
		<p>
			Ну и фиг с ним, с этим <em>finally</em>. Вреда от него не меньше, чем пользы. А может, и больше. Чтобы 
			закончить на мажорной ноте, надо написать немножко поистине безумного кода (рекурсия будет кстати). 
			Вгляните-ка на <a href="#listing-13">листинг 13</a>!
			
<h4 id="listing-13">Листинг 13 - безумный пример использования TWR</h4>
<pre>
     1	public class CrazyTwr {
     2		public static void main(String ignored[]) {
     3			System.out.println("&gt;&gt;&gt; main()");
     4			try ( MyResource resource = new MyResource() ) {
     5				System.out.println("&gt;&gt;&gt; try-block from main()");
     6				throw new IllegalStateException("Exception from main()");
     7			} finally {
     8				System.out.println("&gt;&gt;&gt; finally-block from main()");
     9			}
    10		}
    11	}
    12	
    13	class MyResource implements AutoCloseable {
    14		@Override
    15		public void close() {
    16			System.out.println("&gt;&gt;&gt; MyResource.close()");
    17			try ( MyResource resource = new MyResource() ) {
    18				System.out.println("&gt;&gt;&gt; try-block from MyResource");
    19				throw new IllegalStateException("Exception from MyResource.close()");
    20			} finally {
    21				System.out.println("&gt;&gt;&gt; finally-block from MyResource");
    22			}
    23		}
    24	}
</pre>

		<p>
			Полный вывод программы приведен в отдельном файле 
			<a href="https://github.com/flaz14/flaz14.github.io/blob/master/java-twr/sample/CrazyTwr.txt">CrazyTwr.txt</a> 
			(объем файла - 6 Мебайт, на столько хватило стэка в моем компьютере). Ниже находится краткое содержание:

<pre>
&gt;&gt;&gt; main()
&gt;&gt;&gt; try-block from main()
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; try-block from MyResource
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; try-block from MyResource
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; try-block from MyResource
&gt;&gt;&gt; MyResource.close()
&gt;&gt;&gt; try-block from MyResource
...
&gt;&gt;&gt; MyResource.close()&gt;&gt;&gt; finally-block from MyResource
&gt;&gt;&gt; finally-block from MyResource
&gt;&gt;&gt; finally-block from MyResource
&gt;&gt;&gt; finally-block from MyResource
&gt;&gt;&gt; finally-block from MyResource
...
&gt;&gt;&gt; finally-block from main()
Exception in thread "main" java.lang.IllegalStateException: Exception from main()
        at CrazyTwr.main(CrazyTwr.java:6)
        Suppressed: java.lang.IllegalStateException: Exception from MyResource.close()
                at MyResource.close(CrazyTwr.java:19)
                at CrazyTwr.main(CrazyTwr.java:7)
                Suppressed: java.lang.IllegalStateException: Exception from MyResource.close()
                        at MyResource.close(CrazyTwr.java:19)
                        at MyResource.close(CrazyTwr.java:20)
                        ... 1 more
                        Suppressed: java.lang.IllegalStateException: Exception from MyResource.close()
                                at MyResource.close(CrazyTwr.java:19)
                                at MyResource.close(CrazyTwr.java:20)
...
</pre>

		<p>
			Комментарии, как говорится, излишни. Но "лесенка" красивая получилась :)
		
		<h2>Читайте JLS! Нет, лучше ничего не читайте...</h2>
		
		<p>
			Умные книжки не нужны. Ламерские статьи вроде этой - тоже. Ведь в спецификации все разложено по полочкам. А 
			вообще, спецификация ничего не дает сама по себе. Нужно пробовать писать и ломать программы самостоятельно. 
			Тогда даже в несвежих фичах	языка обязательно откроется что-то новое.
		
        <p>
			__________
			<ol>
				<li id="footnote-1-bottom">
					<p>
						<a href="#footnote-1-top" title="Перейти к основному тексту">&uarr;</a> 
						<a href="https://www.ozon.ru/context/detail/id/24133566/">
							Бенджамин Эванс, Мартин Вербург "Java. Новое поколение разработки"
						</a>

				<li id="footnote-2-bottom">
					<p>
						<a href="#footnote-2-top" title="Перейти к основному тексту">&uarr;</a> 
						<a href="https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html">
							The try-with-resources Statement
						</a>
						
				<li id="footnote-3-bottom">
					<p>
						<a href="#footnote-3-top" title="Перейти к основному тексту">&uarr;</a> 
						Все примеры запускались на Java 8:
<pre>
$ javac -version
javac 1.8.0_111

$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)
</pre>	

				<li id="footnote-4-bottom">
					<p>
						<a href="#footnote-4-top" title="Перейти к основному тексту">&uarr;</a> 
						Несмотря на то, что примеры небольшие, везда стоят номера строк. Так намного удобнее 
						разбираться со стэктрэйсами.

				<li id="footnote-5-bottom">
					<p>
						<a href="#footnote-5-top" title="Перейти к основному тексту">&uarr;</a> 
						Указывать в интерфейсах <code>@Override</code> не смысла. В конце-концов, в интерфейсе мы ничего
						переопределить не можем, поскольку в интерфейсах априори отсутствует реализация (оставим в 
						стороне методы по-умолчанию). Но при объявлении метода, который присутствует в суперинтерфейсе, 
						можно немного переопределить родительский метод. А именно: можно изменить тип выбрасываемого 
						исключение (устоявшаяся практика - объявлять в интерфейсе-наследнике более конкретный тип
						исключения). Или же полностью избавиться от него. Этим я и воспользовался, чтобы убрать 
						надоедливый <code>Exception</code>, тянущийся из <code>AutoCloseable</code>.
			</ol>
		
		<hr>

		<h1>
			<big>
				<a href="#" title="Перейти к началу страницы">&uarr;</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="/" title="Перейти на главную страницу">&#8962;</a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="http://validator.w3.org/check?uri=referer">
					<img src="http://www.w3.org/Icons/valid-html401" alt="Valid HTML 4.01 Strict" 
					height="31" width="88">
				</a>
			</big>
		</h1>
	</body>
</html>